language: java
dist: trusty
sudo: false
jdk:
  - oraclejdk8
  - oraclejdk9
before_install:
  - chmod +x ./gradlew
script:
  - ./gradlew check --stacktrace
  - ./gradlew jacocoTestReport
before_deploy:
  - ./gradlew generateLicenseReport
  - ./gradlew javadoc
  - echo $SIGNING_KEY_SECRING_BASE64 | base64 --decode > ./signing.key.secring
  - export SIGNING_KEY_PATH=./signing.key.secring
  - mkdir -p projectpage
  - cp -rv build/reports/* projectpage
  - cp -rv build/docs/* projectpage
  - cp -rv docs/* projectpage
deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository -DDEPLOYMENT=true
    on:
      tags: true
      jdk: oraclejdk8
  - provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: projectpage
    keep-history: false
    on:
      branch: master
      jdk: oraclejdk9
after_success:
  - bash <(curl -s https://codecov.io/bash)
